version: 2.1

aliases:
  - &restore_cache
    name: Restore cache
    key: v3-cache-{{ checksum "yarn.lock" }}

  - &save_cache
    name: Save cache
    paths:
      - ~/.cache
    key: v3-cache-{{ checksum "yarn.lock" }}

  - &circleci_node
    - image: circleci/node:12.0.0

defaults: &defaults
  docker:
    - image: circleci/node:12.0.0
  working_directory: ~/vue-tabulator

jobs:
  test_build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install peerDependencies
          command: npx @team-griffin/install-self-peers

      - save_cache: *save_cache
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'
            - cypress/*

  lint_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/vue-tabulator
      - run:
          name: Run Lint
          command: yarn lint

  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/vue-tabulator
      - run:
          name: Run Unit Tests
          command: yarn test:unit

  e2e_test:
    <<: *defaults
    docker:
      - image: cypress/base:12
    steps:
      - attach_workspace:
          at: ~/vue-tabulator
      - run: npx cypress install
      - run:
          name: Run E2E
          command: yarn  test:e2e

workflows:
  version: 2

  branch-workflow:
    jobs:
      - test_build
      - lint_test:
          requires:
            - test_build
      - unit_test:
          requires:
            - test_build
      - e2e_test:
          requires:
            - test_build